#!/bin/bash
# Job name
#PBS -N pinn_treino_batch

# Output and error files
#PBS -o saida.out
#PBS -e saida.err

# Walltime (hh:mm:ss)
#PBS -l walltime=60:00:00

# Nodes and cores per node
#PBS -l nodes=compute-1-0:ppn=1

# Change to submission directory
cd $PBS_O_WORKDIR

# List nodes allocated
cat $PBS_NODEFILE


export PATH=/home/yan/.conda/bin:$PATH


# Display GPU information
gpu_count=$(nvidia-smi -L | wc -l)
for (( i=0; i<gpu_count; i++ )); do
    gpu_info=$(nvidia-smi -L | sed -n "$((i+1))p")
    echo "$gpu_info"
    
    mig_count=$(nvidia-smi -i $i --query-gpu=mig.mode.current --format=csv,noheader | grep -c Enabled)
    
    if [ "$mig_count" -gt 0 ]; then
        nvidia-smi -i $i --query-compute-apps=uuid --format=csv,noheader,nounits | while IFS= read -r mig_uuid; do
            echo "  MIG: $mig_uuid"
        done
    else
        echo "  No MIG instances found."
    fi
done
conda activate  env1

# Check GPUs are visible
nvidia-smi

# Launch MPI Python training
time mpiexec --hostfile $PBS_NODEFILE python vi.py

